FROM fccoelho/infodengue-nginx:test


# RUN mkdir /etc/nginx/sites-available/ 
# # RUN mkdir /etc/nginx/sites-enabled/

# RUN mkdir -p /var/www/infodengue
# ADD nginx/index.html /var/www/infodengue/index.html

# RUN rm /etc/nginx/sites-enabled/default

# ADD nginx/default /etc/nginx/sites-available/infodengue.mat.br
# RUN cd /etc/nginx/sites-enabled/ \
# && ln -s ../sites-available/infodengue.mat.br .




# Expose ports
EXPOSE 8080
